// Generated by CoffeeScript 1.7.1
(function() {
  var D, HOST, boot, render,
    __hasProp = {}.hasOwnProperty;

  HOST = '';

  boot = function() {
    var app, mountNode;
    mountNode = document.getElementById('expenses');
    $.couch.urlprefix = HOST;
    app = ExpensesApp({
      db: $.couch.db('comptes')
    });
    return React.renderComponent(app, mountNode);
  };

  document.addEventListener('DOMContentLoaded', boot);

  D = React.DOM;

  this.DebtsList = React.createClass({
    displayName: "DebtsList",
    render: function() {
      return D.article({
        className: "panel panel-default",
        id: "DebtsList"
      }, D.div({
        className: "panel-heading"
      }, D.h3({
        className: "panel-title"
      }, "Who owes what?")), D.table({
        className: "panel-body table table-stripped table-hover"
      }, D.thead(null, D.tr(null, D.th(null, "From", D.th(null, "To", D.th(null, "Amount"))))), D.tbody(null, this.props.debts.map(function(debt) {
        return D.tr(null, D.td(null, debt.from, D.td(null, debt.to, D.td(null, debt.amount))));
      }))));
    }
  });

  D = React.DOM;

  this.ExpensesApp = React.createClass({
    displayName: "ExpensesApp",
    getInitialState: function() {
      return {
        expenses: [],
        text: ""
      };
    },
    componentDidMount: function() {
      this.changes = this.props.db.changes();
      this.changes.onChange(this.fetchData);
      return this.fetchData();
    },
    componentWillUnmount: function() {
      return this.changes.stop();
    },
    fetchData: function() {
      return this.props.db.view("expenseslist/ListOfExpenses", {
        success: (function(_this) {
          return function(view) {
            if (_this.isMounted()) {
              return _this.setState({
                expenses: view.rows.map(function(r) {
                  return r.value;
                })
              });
            }
          };
        })(this),
        error: console.error.bind(console),
        reduce: false
      });
    },
    removeDoc: function(doc, n) {
      return this.props.db.removeDoc(doc);
    },
    addExpense: function(doc) {
      this.props.db.saveDoc(doc);
      this.state.expenses.push(doc);
      return this.setState({
        expenses: this.state.expenses
      });
    },
    expand: function() {
      var expenses;
      expenses = [];
      this.state.expenses.forEach(function(exp) {
        return exp.tos.forEach(function(to) {
          return expenses.push({
            from: exp.from,
            to: to,
            amount: -exp.amount / exp.tos.length
          });
        });
      });
      return expenses;
    },
    simplify: function() {
      return debts.simplify(this.expand());
    },
    allUsers: function() {
      var name, userDebts, users;
      users = [];
      userDebts = debts.totalize(this.expand());
      for (name in userDebts) {
        if (!__hasProp.call(userDebts, name)) continue;
        users.push({
          name: name,
          amount: userDebts[name]
        });
      }
      return users;
    },
    render: function() {
      return D.section({
        id: "app"
      }, D.div({
        className: "col-md-6"
      }, NewExpenseForm({
        addExpense: this.addExpense,
        userNames: this.allUsers().map(function(u) {
          return u.name;
        })
      }), ExpensesList({
        expenses: this.state.expenses,
        removeDoc: this.removeDoc
      })), D.div({
        className: "col-md-6"
      }, DebtsList({
        debts: this.simplify()
      }), UsersList({
        users: this.allUsers()
      })));
    }
  });

  D = React.DOM;

  this.ExpensesList = React.createClass({
    displayName: "ExpensesList",
    mkDeleteFunc: function(doc, n) {
      return (function(_this) {
        return function(evt) {
          if (confirm("Are you sure?")) {
            return _this.props.removeDoc(doc, n);
          }
        };
      })(this);
    },
    render: function() {
      return D.article({
        className: "panel panel-default",
        id: "ExpensesList"
      }, D.div({
        className: "panel-heading"
      }, D.h3({
        className: "panel-title"
      }, "List of all expenses")), D.ul({
        className: "panel-body list-group"
      }, this.props.expenses.map((function(_this) {
        return function(exp, n) {
          return D.li({
            className: "list-group-item"
          }, D.h4({
            className: "list-group-item-heading"
          }, D.span({
            className: "label label-info"
          }, exp.amount), " ", exp.description), D.div({
            className: "list-group-item-text"
          }, D.p(null, "By ", D.b(null, exp.from), "."), D.p(null, "For " + exp.tos.join(", ") + "."), D.button({
            className: "btn",
            onClick: _this.mkDeleteFunc(exp, n)
          }, D.span({
            className: "glyphicon glyphicon-trash"
          }), "Delete")));
        };
      })(this))));
    }
  });

  D = React.DOM;

  this.NewExpenseForm = React.createClass({
    displayName: "NewExpenseForm",
    handleSubmit: function(evt) {
      var doc;
      evt.preventDefault();
      doc = {
        description: this.val("description").trim(),
        from: this.from.trim(),
        tos: this.to,
        amount: Math.round(parseFloat(this.val("amount")) * 100) / 100,
        date: new Date().toISOString()
      };
      if (!doc.description || !doc.from || !doc.tos.length) {
        return;
      }
      this.props.addExpense(doc);
      this.refs.form.getDOMNode().reset();
      return this.refs.description.getDOMNode().focus();
    },
    val: function(name) {
      if (name in this.refs) {
        return this.refs[name].getDOMNode().value;
      } else {
        return "";
      }
    },
    setFunc: function(name) {
      return (function(_this) {
        return function(val) {
          return _this[name] = val;
        };
      })(this);
    },
    render: render = function() {
      return D.article({
        className: "panel panel-default"
      }, D.div({
        className: "panel-heading"
      }, D.h2({
        className: "panel-title"
      }, "Add a new expense")), D.form({
        onSubmit: this.handleSubmit,
        ref: "form",
        role: "form"
      }, D.input({
        className: "form-control",
        placeholder: "Description",
        ref: "description",
        required: true
      }), UserSelect({
        onChange: this.setFunc("from"),
        userNames: this.props.userNames,
        multiple: false,
        placeholder: "Who paid?"
      }), UserSelect({
        onChange: this.setFunc("to"),
        userNames: this.props.userNames,
        multiple: true,
        placeholder: "For who?"
      }), D.input({
        className: "form-control",
        type: "number",
        placeholder: "How much money?",
        ref: "amount",
        required: true,
        min: 0,
        step: 0.01
      }), D.button({
        className: "btn btn-primary"
      }, "Add")));
    }
  });

  D = React.DOM;

  this.UsersList = React.createClass({
    displayName: "UserList",
    render: function() {
      return D.article({
        className: "panel panel-default"
      }, D.div({
        className: "panel-heading"
      }, D.h3({
        className: "panel-title"
      }, "User accounts")), D.table({
        className: "panel-body table table-stripped table-hover"
      }, D.thead(null, D.tr(null, D.th(null, "User", D.th(null, "Total")))), D.tbody(null, this.props.users.map(function(user) {
        return D.tr(null, D.td(null, user.name), D.td(null, user.amount));
      }))));
    }
  });

  D = React.DOM;

  this.UserSelect = React.createClass({
    displayName: "UserSelect",
    attachSelect2: function() {
      return $(this.getDOMNode()).select2({
        tags: this.props.userNames,
        tokenSeparators: [","],
        maximumSelectionSize: (this.props.multiple ? -1 : 1),
        formatNoMatches: "",
        width: "100%",
        sortResults: function(results, container, query) {
          if (results.length > 0 && results[0].text === query.term) {
            results.push(results.shift());
          }
          return results;
        }
      }).select2("val", this.props.multiple ? this.props.userNames : []).on("change", this.change);
    },
    componentDidMount: function() {
      this.attachSelect2();
    },
    componentWillUnmount: function() {
      $(this.getDOMNode()).off("change", this.change);
    },
    componentDidUpdate: function() {
      this.attachSelect2();
    },
    change: function() {
      var val;
      val = $(this.getDOMNode()).select2("val");
      this.props.onChange((this.props.multiple ? val : val[0]));
    },
    render: function() {
      return D.input({
        type: "hidden",
        placeholder: this.props.placeholder,
        defaultValue: (this.props.multiple ? this.props.userNames.join(", ") : "")
      });
    }
  });

}).call(this);
